### ISSUE TITLE
nodejs rules fail hermetic build property

### ISSUE THREAD

**Issue by daniel-sudz** [bazelbuild/reclient#52]
One some machines `logrecordserver` fails to build. It appears as though npm/node path fails to resolve correctly and swaps to global path instead of bazel build path. It seems like he maintenance for `@nodejs//nodejs` has mostly migrated to https://github.com/aspect-build/rules_js.

```bash
[473 / 938] Compiling src/google/protobuf/descriptor.cc [for tool]; 11s linux-sandbox ... (6 actions running)
ERROR: /mnt/vss/_work/1/s/chromium.reclient/internal/pkg/logrecordserver/ui/BUILD.bazel:4:8: Executing genrule //internal/pkg/logrecordserver/ui:reproxytool_ui_tar_gen failed: (Exit 254): bash failed: error executing Genrule command (from target //internal/pkg/logrecordserver/ui:reproxytool_ui_tar_gen) 
  (cd /mnt/vss/_work/1/_bazel/98b910cd1130ae71cc5ae6d07bf0de01/sandbox/linux-sandbox/408/execroot/_main && \
  exec env - \
    PATH=/bin:/usr/bin:/usr/local/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; export PATH=$PATH:$PWD/$(dirname external/nodejs_linux_amd64/bin/npm) && export ROOT=$PWD ;echo "Installing angular..." ; cd internal/pkg/logrecordserver/ui/app ; $ROOT/external/nodejs_linux_amd64/bin/npm ci ;echo "Building app" ; node_modules/.bin/ng build ;cd $ROOT ; tar cvf bazel-out/k8-opt/bin/internal/pkg/logrecordserver/ui/reproxytool_ui.tar internal/pkg/logrecordserver/ui/app/dist/reproxyui/browser')
# Configuration: e4957d82c24a0731d0975e5f824cc12157307b7d4a84434d0e23d68f71dad7d3
# Execution platform: @@local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
npm WARN logfile Error: ENOENT: no such file or directory, scandir '/home/cloudtest/.npm/_logs'
npm WARN logfile     at async Object.readdir (node:internal/fs/promises:945:18)
npm WARN logfile     at async #cleanLogs (/tmp/bazel-source-roots/1/bin/nodejs/lib/node_modules/npm/lib/utils/log-file.js:207:19)
npm WARN logfile  error cleaning log files Error: ENOENT: no such file or directory, scandir '/home/cloudtest/.npm/_logs'
npm WARN logfile     at async Object.readdir (node:internal/fs/promises:945:18)
npm WARN logfile     at async #cleanLogs (/tmp/bazel-source-roots/1/bin/nodejs/lib/node_modules/npm/lib/utils/log-file.js:207:19) {
npm WARN logfile   errno: -2,
npm WARN logfile   code: 'ENOENT',
npm WARN logfile   syscall: 'scandir',
npm WARN logfile   path: '/home/cloudtest/.npm/_logs'
npm WARN logfile }
npm notice 
npm notice New minor version of npm available! 10.5.2 -> 10.8.1
npm notice Changelog: <[https://github.com/npm/cli/releases/tag/v10.8.1>](https://github.com/npm/cli/releases/tag/v10.8.1%3E)
npm notice Run `npm install -g npm@10.8.1` to update!
npm notice 
npm ERR! code ENOENT
npm ERR! syscall mkdir
npm ERR! path /home/cloudtest/.npm
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, mkdir '/home/cloudtest/.npm'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Log files were not written due to an error writing to the directory: /home/cloudtest/.npm/_logs
npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal
Installing angular...
INFO: Elapsed time: 153.546s, Critical Path: 60.89s
INFO: 479 processes: 76 internal, 403 linux-sandbox.
ERROR: Build did NOT complete successfully
```

**Comment by bentekkie** [comment]
Thanks, for the report, reproxytool (which is what depends on this) is currently under development and is not quite stable yet. 
For building all stable binaries I would suggest targeting `//:artifacts_tar`

**Comment by gkousik** [comment]
What does your `bazel` build invocation look like?

**Comment by daniel-sudz** [comment]
> What does your `bazel` build invocation look like?

related to https://github.com/bazelbuild/reclient/issues/51#issuecomment-2174355274 but how about I contribute a github actions yaml file with the steps that I use to try to build the repo? That way there is a repeatable way to communicate these type of issues.

**Comment by daniel-sudz** [comment]
> What does your `bazel` build invocation look like?

this should be reproducible by uninstalling any user/local installed nodejs and running the same thing as https://github.com/bazelbuild/reclient/blob/main/.github/workflows/main.yaml. I am not very experienced with the bazel ecosystem as a whole but my understanding is that we should be using the build-specific node version

**Comment by daniel-sudz** [comment]
here's a full build log with everything: https://github.com/daniel-sudz/reclient/pull/2

**Comment by bentekkie** [comment]
Thanks for the repro steps, it looks like the order of the path is wrong in our genrule, should be a simple fix that we can land early next week
